### ISSUE TITLE
Invalid DISPLAY variable

### ISSUE THREAD

**Issue by GabrielLin** [jiny2001/dcscn-super-resolution#4]
After training, there is an error at model.save_graphs(flags.graph_dir, trial)

Traceback (most recent call last):
  File "train.py", line 99, in <module>
    tf.app.run()
  File "/opt/anaconda2/envs/tf121py35/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train.py", line 44, in main
    train(model, FLAGS, i)
  File "train.py", line 89, in train
    model.save_graphs(flags.graph_dir, trial)
  File "/data1/xxx/cv/dcscn-super-resolution/DCSCN.py", line 513, in save_graphs
    plt.plot(self.csv_epochs, self.csv_training_psnr, "b", label='Training PSNR')
  File "/opt/anaconda2/envs/tf121py35/lib/python3.5/site-packages/matplotlib/pyplot.py", line 3306, in plot
    ax = gca()
  File "/opt/anaconda2/envs/tf121py35/lib/python3.5/site-packages/matplotlib/pyplot.py", line 950, in gca
    return gcf().gca(**kwargs)
  File "/opt/anaconda2/envs/tf121py35/lib/python3.5/site-packages/matplotlib/pyplot.py", line 586, in gcf
    return figure()
  File "/opt/anaconda2/envs/tf121py35/lib/python3.5/site-packages/matplotlib/pyplot.py", line 535, in figure
    **kwargs)
  File "/opt/anaconda2/envs/tf121py35/lib/python3.5/site-packages/matplotlib/backends/backend_qt5agg.py", line 44, in new_figure_manager
    return new_figure_manager_given_figure(num, thisFig)
  File "/opt/anaconda2/envs/tf121py35/lib/python3.5/site-packages/matplotlib/backends/backend_qt5agg.py", line 51, in new_figure_manager_given_figure
    canvas = FigureCanvasQTAgg(figure)
  File "/opt/anaconda2/envs/tf121py35/lib/python3.5/site-packages/matplotlib/backends/backend_qt5agg.py", line 242, in __init__
    super(FigureCanvasQTAgg, self).__init__(figure=figure)
  File "/opt/anaconda2/envs/tf121py35/lib/python3.5/site-packages/matplotlib/backends/backend_qt5agg.py", line 66, in __init__
    super(FigureCanvasQTAggBase, self).__init__(figure=figure)
  File "/opt/anaconda2/envs/tf121py35/lib/python3.5/site-packages/matplotlib/backends/backend_qt5.py", line 236, in __init__
    _create_qApp()
  File "/opt/anaconda2/envs/tf121py35/lib/python3.5/site-packages/matplotlib/backends/backend_qt5.py", line 144, in _create_qApp
    raise RuntimeError('Invalid DISPLAY variable')
RuntimeError: Invalid DISPLAY variable

**Comment by jiny2001** [comment]
Hi, I'm not sure about the error. Some specific environments will cause the error?

Could you check this link below?
https://stackoverflow.com/questions/35737116/runtimeerror-invalid-display-variable

Or you can just comment out the line below.
File "/data1/xxx/cv/dcscn-super-resolution/DCSCN.py", line 513, in save_graphs
plt.plot(self.csv_epochs, self.csv_training_psnr, "b", label='Training PSNR')

**Comment by GabrielLin** [comment]
Thank. I will tried later, now the GPU is occupied.

**Comment by GabrielLin** [comment]
I add:
`matplotlib.use('Agg')`
There is no error shown now. But the PSNR.png has no data, only coordinate.

**Comment by jiny2001** [comment]
Thanks, Let me think  what is the best solution for this issue.

**Comment by GabrielLin** [comment]
Waiting you. Thanks.

**Comment by GabrielLin** [comment]
Now the PSNR.png has data. I do not why it cannot shew the data last time. Maybe it is my fault.

**Comment by jiny2001** [comment]
Hi, that is great.
Since I don't call show() method in my code, I'm not sure why matplot is trying to open a graph-window. However, adding matplotlib.use('Agg') is a good choice. You can send me a pull request or I will modify it later. Thanks. :)

**Comment by GabrielLin** [comment]
This is my import part:
`
import logging
import os
import random
import time

import matplotlib

matplotlib.use('agg')
import matplotlib.pylab as plt
import numpy as np
import tensorflow as tf

from helper import loader, utilty as util
`

I reformat the code by my own style of tab and space. As a result, pull request might not suitable. There will be a lot of difference.

**Comment by jiny2001** [comment]
Thanks!
I updated codes.
