### ISSUE TITLE
Nan in summary histogram

### ISSUE THREAD

**Issue by ManoaNosea** [jiny2001/dcscn-super-resolution#60]
''λ python train.py --dataset=d3mod_y_8 --test_dataset=d3mod_y_8 --training_images=1000 --scale=4 --batch_image_size=32 --layers=6 --filters=22 --nin_filters=22 --batch_num=1
Python Interpreter version:3.6
tensorflow version:1.12.0
numpy version:1.15.1
2018-11-22 11:43:39.591517: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2018-11-22 11:43:39.797543: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties:
name: GeForce GTX 780 Ti major: 3 minor: 5 memoryClockRate(GHz): 1.0195
pciBusID: 0000:02:00.0
totalMemory: 3.00GiB freeMemory: 2.88GiB
2018-11-22 11:43:39.797543: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2018-11-22 11:43:39.800543: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-11-22 11:43:39.801043: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0
2018-11-22 11:43:39.801043: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N
2018-11-22 11:43:39.801043: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 2795 MB memory) -> physical GPU (device: 0, name: GeForce GTX 780 Ti, pci bus id: 0000:02:00.0, compute capability: 3.5)
Session and graph initialized.
2018-11-22 11:43:39.803544: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2018-11-22 11:43:39.803544: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-11-22 11:43:39.803544: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0
2018-11-22 11:43:39.804044: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N
2018-11-22 11:43:39.804044: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 2795 MB memory) -> physical GPU (device: 0, name: GeForce GTX 780 Ti, pci bus id: 0000:02:00.0, compute capability: 3.5)

DCSCN v2-------------------------------------
2018/11/22 11:43:39 [dcscn_L6_F22to22_Sc4_NIN_A22_B32_PS_R1F32]
Feature:22 22 22 22 22 22  Total: (132)22 32 32 216 216 1  Complexity:249,628 Receptive Fields:19
CNN1/conv_W:0 (3, 3, 1, 22)=198, CNN1/conv_B:0 22, CNN1/prelu/CNN1_prelu:0 22, CNN2/conv_W:0 (3, 3, 22, 22)=4356, CNN2/conv_B:0 22, CNN2/prelu/CNN2_prelu:0 22, CNN3/conv_W:0 (3, 3, 22, 22)=4356, CNN3/conv_B:0 22, CNN3/prelu/CNN3_prelu:0 22, CNN4/conv_W:0 (3, 3, 22, 22)=4356, CNN4/conv_B:0 22, CNN4/prelu/CNN4_prelu:0 22, CNN5/conv_W:0 (3, 3, 22, 22)=4356, CNN5/conv_B:0 22, CNN5/prelu/CNN5_prelu:0 22, CNN6/conv_W:0 (3, 3, 22, 22)=4356, CNN6/conv_B:0 22, CNN6/prelu/CNN6_prelu:0 22, A1/conv_W:0 (1, 1, 132, 22)=2904, A1/conv_B:0 22, A1/prelu/A1_prelu:0 22, B1/conv_W:0 (1, 1, 132, 32)=4224, B1/conv_B:0 32, B1/prelu/B1_prelu:0 32, B2/conv_W:0 (3, 3, 32, 32)=9216, B2/conv_B:0 32, B2/prelu/B2_prelu:0 32, Up-PS/Up-PS_CNN/conv_W:0 (3, 3, 54, 216)=104976, Up-PS/Up-PS_CNN/conv_B:0 216, Up-PS2/Up-PS2_CNN/conv_W:0 (3, 3, 54, 216)=104976, Up-PS2/Up-PS2_CNN/conv_B:0 216, R-CNN1/conv_W:0 (3, 3, 54, 1)=486,
Total 32 variables, 249,628 params

['train.py', '--dataset=d3mod_y_8', '--test_dataset=d3mod_y_8', '--training_images=1000', '--scale=4', '--batch_image_size=32', '--layers=6', '--filters=22', '--nin_filters=22', '--batch_num=1']
Test Data:d3mod_y_8 Training Data:d3mod_y_8
Total 32 variables, 249,628 params
Model initialized.
2018-11-22 11:43:52.521659: W tensorflow/core/common_runtime/bfc_allocator.cc:211] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.37GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2018-11-22 11:43:52.682179: W tensorflow/core/common_runtime/bfc_allocator.cc:211] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.93GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
D:\Programs64\Python-3.6.5\lib\site-packages\skimage\util\arraycrop.py:177: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  cropped = ar[slices]
2018-11-22 11:43:54.006347: W tensorflow/core/common_runtime/bfc_allocator.cc:211] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.90GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2018-11-22 11:43:55.633054: W tensorflow/core/common_runtime/bfc_allocator.cc:211] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.19GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2018-11-22 11:43:56.287137: W tensorflow/core/common_runtime/bfc_allocator.cc:211] Allocator (GPU_0_bfc) ran out of memory trying to allocate 3.87GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2018-11-22 11:43:56.559171: W tensorflow/core/common_runtime/bfc_allocator.cc:211] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.19GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2018-11-22 11:43:57.225256: W tensorflow/core/common_runtime/bfc_allocator.cc:211] Allocator (GPU_0_bfc) ran out of memory trying to allocate 3.87GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2018-11-22 11:43:58.187878: W tensorflow/core/common_runtime/bfc_allocator.cc:211] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.45GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2018-11-22 11:43:59.424535: W tensorflow/core/common_runtime/bfc_allocator.cc:211] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.19GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2018-11-22 11:43:59.734075: W tensorflow/core/common_runtime/bfc_allocator.cc:211] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.19GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
Initial PSNR:nan SSIM:nan
Traceback (most recent call last):
  File "D:\Programs64\Python-3.6.5\lib\site-packages\tensorflow\python\client\session.py", line 1334, in _do_call
    return fn(*args)
  File "D:\Programs64\Python-3.6.5\lib\site-packages\tensorflow\python\client\session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "D:\Programs64\Python-3.6.5\lib\site-packages\tensorflow\python\client\session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Nan in summary histogram for: CNN1/output/dcscn_L6_F22to22_Sc4_NIN_A22_B32_PS_R1F32
         [[{{node CNN1/output/dcscn_L6_F22to22_Sc4_NIN_A22_B32_PS_R1F32}} = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](CNN1/output/dcscn_L6_F22to22_Sc4_NIN_A22_B32_PS_R1F32/tag, CNN1/dropout/mul/_29)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 136, in <module>
    tf.app.run()
  File "D:\Programs64\Python-3.6.5\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "train.py", line 53, in main
    psnr, ssim = train(model, FLAGS, i)
  File "train.py", line 84, in train
    model.log_to_tensorboard(test_filenames[0], psnr, save_meta_data=True)
  File "Q:\theshitt-backup\Projects\AINeuralNetSuperRes\DCSCNv2-Sep-17\DCSCN.py", line 421, in log_to_tensorboard
    summary_str, _ = self.sess.run([self.summary_op, self.loss], feed_dict=feed_dict)
  File "D:\Programs64\Python-3.6.5\lib\site-packages\tensorflow\python\client\session.py", line 929, in run
    run_metadata_ptr)
  File "D:\Programs64\Python-3.6.5\lib\site-packages\tensorflow\python\client\session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "D:\Programs64\Python-3.6.5\lib\site-packages\tensorflow\python\client\session.py", line 1328, in _do_run
    run_metadata)
  File "D:\Programs64\Python-3.6.5\lib\site-packages\tensorflow\python\client\session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Nan in summary histogram for: CNN1/output/dcscn_L6_F22to22_Sc4_NIN_A22_B32_PS_R1F32
         [[node CNN1/output/dcscn_L6_F22to22_Sc4_NIN_A22_B32_PS_R1F32 (defined at Q:\theshitt-backup\Projects\AINeuralNetSuperRes\DCSCNv2-Sep-17\helper\utilty.py:435)  = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](CNN1/output/dcscn_L6_F22to22_Sc4_NIN_A22_B32_PS_R1F32/tag, CNN1/dropout/mul/_29)]]

Caused by op 'CNN1/output/dcscn_L6_F22to22_Sc4_NIN_A22_B32_PS_R1F32', defined at:
  File "train.py", line 136, in <module>
    tf.app.run()
  File "D:\Programs64\Python-3.6.5\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "train.py", line 42, in main
    model.build_graph()
  File "Q:\theshitt-backup\Projects\AINeuralNetSuperRes\DCSCNv2-Sep-17\DCSCN.py", line 213, in build_graph
    use_batch_norm=self.batch_norm, dropout_rate=self.dropout_rate)
  File "Q:\theshitt-backup\Projects\AINeuralNetSuperRes\DCSCNv2-Sep-17\helper\tf_graph.py", line 133, in build_conv
    util.add_summaries("output", self.name, h, save_stddev=True, save_mean=True)
  File "Q:\theshitt-backup\Projects\AINeuralNetSuperRes\DCSCNv2-Sep-17\helper\utilty.py", line 435, in add_summaries
    tf.summary.histogram(header_name + model_name, var)
  File "D:\Programs64\Python-3.6.5\lib\site-packages\tensorflow\python\summary\summary.py", line 187, in histogram
    tag=tag, values=values, name=scope)
  File "D:\Programs64\Python-3.6.5\lib\site-packages\tensorflow\python\ops\gen_logging_ops.py", line 311, in histogram_summary
    "HistogramSummary", tag=tag, values=values, name=name)
  File "D:\Programs64\Python-3.6.5\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "D:\Programs64\Python-3.6.5\lib\site-packages\tensorflow\python\util\deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "D:\Programs64\Python-3.6.5\lib\site-packages\tensorflow\python\framework\ops.py", line 3274, in create_op
    op_def=op_def)
  File "D:\Programs64\Python-3.6.5\lib\site-packages\tensorflow\python\framework\ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Nan in summary histogram for: CNN1/output/dcscn_L6_F22to22_Sc4_NIN_A22_B32_PS_R1F32
         [[node CNN1/output/dcscn_L6_F22to22_Sc4_NIN_A22_B32_PS_R1F32 (defined at Q:\theshitt-backup\Projects\AINeuralNetSuperRes\DCSCNv2-Sep-17\helper\utilty.py:435)  = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](CNN1/output/dcscn_L6_F22to22_Sc4_NIN_A22_B32_PS_R1F32/tag, CNN1/dropout/mul/_29)]]''

**Comment by jiny2001** [comment]
NaN in the hidden layer output means, I believe it diverged to infinity.

Which means your hyper parameter setting is not good. You should use more stable hyper parameter like lower learning late or larger batch num or lager gradient clipping. Please try it.
