### ISSUE TITLE
train in linux

### ISSUE THREAD

**Issue by violetsaturn** [jiny2001/dcscn-super-resolution#79]
hello，thank you for your code , i have one problem about the environment. i can run the code on my computer with windows operating system，but the code can't run on the linux system with the gpu，cloud you help me ?

Traceback (most recent call last):
  File "train.py", line 17, in <module>
    import DCSCN
  File "/home/ljx/dcscn-super-resolution/DCSCN.py", line 21, in <module>
    from helper import loader, tf_graph, utilty as util
  File "/home/ljx/dcscn-super-resolution/helper/loader.py", line 127
    print('.', end='', flush=True)
                  ^
SyntaxError: invalid syntax

this is the error, but it not exit when run under the windows operating system.

**Comment by violetsaturn** [comment]
ok， i have a try and solve the SyntaxError: invalid syntax, but now there are another problem......
i use your default parameter for training ,and there is a error:
Python Interpreter version:2.7
tensorflow version:1.4.0
numpy version:1.13.3
Session and graph initialized.
2019-05-08 19:38:56.210998: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2019-05-08 19:39:01.352414: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: 
name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
pciBusID: 0000:86:00.0
totalMemory: 11.17GiB freeMemory: 11.10GiB
2019-05-08 19:39:01.352537: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: Tesla K80, pci bus id: 0000:86:00.0, compute capability: 3.7)

DCSCN v2-------------------------------------
2019/5/8 19:39:1 [dcscn_L12_F196to48_NIN_A64_PS_R1F32]
Feature:196 166 148 133 120 108 97 86 76 66 57 48  Total: (1301)64 32 32 384 1  Complexity:1,754,942 Receptive Fields:29
CNN1/conv_W:0 (3, 3, 1, 196)=1764, CNN1/conv_B:0 196, CNN1/prelu/CNN1_prelu:0 196, CNN2/conv_W:0 (3, 3, 196, 166)=292824, CNN2/conv_B:0 166, CNN2/prelu/CNN2_prelu:0 166, CNN3/conv_W:0 (3, 3, 166, 148)=221112, CNN3/conv_B:0 148, CNN3/prelu/CNN3_prelu:0 148, CNN4/conv_W:0 (3, 3, 148, 133)=177156, CNN4/conv_B:0 133, CNN4/prelu/CNN4_prelu:0 133, CNN5/conv_W:0 (3, 3, 133, 120)=143640, CNN5/conv_B:0 120, CNN5/prelu/CNN5_prelu:0 120, CNN6/conv_W:0 (3, 3, 120, 108)=116640, CNN6/conv_B:0 108, CNN6/prelu/CNN6_prelu:0 108, CNN7/conv_W:0 (3, 3, 108, 97)=94284, CNN7/conv_B:0 97, CNN7/prelu/CNN7_prelu:0 97, CNN8/conv_W:0 (3, 3, 97, 86)=75078, CNN8/conv_B:0 86, CNN8/prelu/CNN8_prelu:0 86, CNN9/conv_W:0 (3, 3, 86, 76)=58824, CNN9/conv_B:0 76, CNN9/prelu/CNN9_prelu:0 76, CNN10/conv_W:0 (3, 3, 76, 66)=45144, CNN10/conv_B:0 66, CNN10/prelu/CNN10_prelu:0 66, CNN11/conv_W:0 (3, 3, 66, 57)=33858, CNN11/conv_B:0 57, CNN11/prelu/CNN11_prelu:0 57, CNN12/conv_W:0 (3, 3, 57, 48)=24624, CNN12/conv_B:0 48, CNN12/prelu/CNN12_prelu:0 48, A1/conv_W:0 (1, 1, 1301, 64)=83264, A1/conv_B:0 64, A1/prelu/A1_prelu:0 64, B1/conv_W:0 (1, 1, 1301, 32)=41632, B1/conv_B:0 32, B1/prelu/B1_prelu:0 32, B2/conv_W:0 (3, 3, 32, 32)=9216, B2/conv_B:0 32, B2/prelu/B2_prelu:0 32, Up-PS/Up-PS_CNN/conv_W:0 (3, 3, 96, 384)=331776, Up-PS/Up-PS_CNN/conv_B:0 384, R-CNN1/conv_W:0 (3, 3, 96, 1)=864, 
Total 48 variables, 1,754,942 params

['train.py']
Test Data:set5 Training Data:bsd200
Total 48 variables, 1,754,942 params
Model initialized.
Initial PSNR:11.984261 SSIM:0.758720
Traceback (most recent call last):
  File "train.py", line 126, in <module>
    tf.app.run()
  File "/usr/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train.py", line 46, in main
    psnr, ssim = train(model, FLAGS, i)
  File "train.py", line 81, in train
    model.build_input_batch()
  File "/home/ljx/dcscn-super-resolution/DCSCN.py", line 185, in build_input_batch
    self.max_value)
  File "/home/ljx/dcscn-super-resolution/helper/loader.py", line 322, in load_batch_image
    input_image = util.resize_image_by_pil(image, 1 / self.scale)
  File "/home/ljx/dcscn-super-resolution/helper/utilty.py", line 229, in resize_image_by_pil
    image = image.resize([new_width, new_height], resample=method)
  File "/usr/lib64/python2.7/site-packages/PIL/Image.py", line 1745, in resize
    return self._new(self.im.resize(size, resample, box))
ValueError: height and width must be > 0
[ljx@cu04 dcscn-super-resolution]$ python train.py
Python Interpreter version:2.7
tensorflow version:1.4.0
numpy version:1.13.3
Session and graph initialized.
2019-05-08 19:45:48.659111: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2019-05-08 19:45:54.295756: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: 
name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
pciBusID: 0000:86:00.0
totalMemory: 11.17GiB freeMemory: 11.10GiB
2019-05-08 19:45:54.295858: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: Tesla K80, pci bus id: 0000:86:00.0, compute capability: 3.7)

DCSCN v2-------------------------------------
2019/5/8 19:45:54 [dcscn_L12_F196to48_NIN_A64_PS_R1F32]
Feature:196 166 148 133 120 108 97 86 76 66 57 48  Total: (1301)64 32 32 384 1  Complexity:1,754,942 Receptive Fields:29
CNN1/conv_W:0 (3, 3, 1, 196)=1764, CNN1/conv_B:0 196, CNN1/prelu/CNN1_prelu:0 196, CNN2/conv_W:0 (3, 3, 196, 166)=292824, CNN2/conv_B:0 166, CNN2/prelu/CNN2_prelu:0 166, CNN3/conv_W:0 (3, 3, 166, 148)=221112, CNN3/conv_B:0 148, CNN3/prelu/CNN3_prelu:0 148, CNN4/conv_W:0 (3, 3, 148, 133)=177156, CNN4/conv_B:0 133, CNN4/prelu/CNN4_prelu:0 133, CNN5/conv_W:0 (3, 3, 133, 120)=143640, CNN5/conv_B:0 120, CNN5/prelu/CNN5_prelu:0 120, CNN6/conv_W:0 (3, 3, 120, 108)=116640, CNN6/conv_B:0 108, CNN6/prelu/CNN6_prelu:0 108, CNN7/conv_W:0 (3, 3, 108, 97)=94284, CNN7/conv_B:0 97, CNN7/prelu/CNN7_prelu:0 97, CNN8/conv_W:0 (3, 3, 97, 86)=75078, CNN8/conv_B:0 86, CNN8/prelu/CNN8_prelu:0 86, CNN9/conv_W:0 (3, 3, 86, 76)=58824, CNN9/conv_B:0 76, CNN9/prelu/CNN9_prelu:0 76, CNN10/conv_W:0 (3, 3, 76, 66)=45144, CNN10/conv_B:0 66, CNN10/prelu/CNN10_prelu:0 66, CNN11/conv_W:0 (3, 3, 66, 57)=33858, CNN11/conv_B:0 57, CNN11/prelu/CNN11_prelu:0 57, CNN12/conv_W:0 (3, 3, 57, 48)=24624, CNN12/conv_B:0 48, CNN12/prelu/CNN12_prelu:0 48, A1/conv_W:0 (1, 1, 1301, 64)=83264, A1/conv_B:0 64, A1/prelu/A1_prelu:0 64, B1/conv_W:0 (1, 1, 1301, 32)=41632, B1/conv_B:0 32, B1/prelu/B1_prelu:0 32, B2/conv_W:0 (3, 3, 32, 32)=9216, B2/conv_B:0 32, B2/prelu/B2_prelu:0 32, Up-PS/Up-PS_CNN/conv_W:0 (3, 3, 96, 384)=331776, Up-PS/Up-PS_CNN/conv_B:0 384, R-CNN1/conv_W:0 (3, 3, 96, 1)=864, 
Total 48 variables, 1,754,942 params

['train.py']
Test Data:set5 Training Data:bsd200
Total 48 variables, 1,754,942 params
Model initialized.
Initial PSNR:15.915055 SSIM:0.791128
Traceback (most recent call last):
  File "train.py", line 126, in <module>
    tf.app.run()
  File "/usr/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train.py", line 46, in main
    psnr, ssim = train(model, FLAGS, i)
  File "train.py", line 81, in train
    model.build_input_batch()
  File "/home/ljx/dcscn-super-resolution/DCSCN.py", line 185, in build_input_batch
    self.max_value)
  File "/home/ljx/dcscn-super-resolution/helper/loader.py", line 322, in load_batch_image
    input_image = util.resize_image_by_pil(image, 1 / self.scale)
  File "/home/ljx/dcscn-super-resolution/helper/utilty.py", line 229, in resize_image_by_pil
    image = image.resize([new_width, new_height], resample=method)
  File "/usr/lib64/python2.7/site-packages/PIL/Image.py", line 1745, in resize
    return self._new(self.im.resize(size, resample, box))
ValueError: height and width must be > 0

i am confused about it and can't solve it!   cloud you solve this problem? thank you very much

**Comment by jiny2001** [comment]
Oops, sorry for late reply. I was a little away from internet.
I guess you have already resolved it but it only runs with python3. Hope your project is going well. Thx!
